version: "3"
services:
  synthea:
      build: 
        dockerfile: Syntheadockerfile       
      volumes:
      - ./output:/synthea/output   
      networks:
        - cloudbuild
        - default
volumes:
  hapi-fhir-postgres:
  
networks:
  cloudbuild:
    external: true
    name: cloudbuild # Needed for Continuous integration
