batch:
  chunkSize: 5000
  throttleLimit: 4
  pagingSize: 100000

logging:
  level:
    org:
      miracum: INFO

spring:
  main:
    banner-mode: false
    allow-bean-definition-overriding: true
    web-application-type: none
  #profiles:
  #  active: dev
  application:
    name: "fhir-to-omop"
  cache.caffeine.spec.maximumSize: 5000

data:
  fhirGateway:
    jdbcUrl: ""
    username: ""
    password: ""
    tableName: "resources"
  fhirServer:
    baseUrl: "http://127.0.0.1:8080/fhir"
    username: ""
    password: ""
    token: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwbmhTQms5c28wOTJvNzJYY09Tb1JhM0pjNXZ1WElmaUFBWHM0aHp0MVlVIn0.eyJleHAiOjE3MDU2MDc5NjUsImlhdCI6MTcwNTU3MTk2NSwianRpIjoiZmUyYTVlM2QtY2UyNy00ZjQxLTk3YjctMTcwNzk2MjhmMDIxIiwiaXNzIjoiaHR0cDovLzEwLjEwMi4xMC4xMTo4MDgxL2F1dGgvcmVhbG1zL2ZoaXItaGFwaSIsInN1YiI6ImY3ZDZlMGRhLTllZjEtNDAwOC1iNTUyLTBmZjNhMzcwNmZkMiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImZoaXItaGFwaS1zZXJ2ZXIiLCJzZXNzaW9uX3N0YXRlIjoiMzRhYjBkZTEtZDhmZC00ZTQ2LWEzMTUtZGQ2ZDVhNmRjODk3IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJodHRwOi8vMTAuMTAyLjEwLjExOjgwODUiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1maGlyLWhhcGkiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImZoaXItaGFwaS1zZXJ2ZXIiOnsicm9sZXMiOlsiZGV2Iiwic3VwZXJ1c2VyIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiMzRhYjBkZTEtZDhmZC00ZTQ2LWEzMTUtZGQ2ZDVhNmRjODk3IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJram9pc0BpcHJkZ3JvdXAuY29tIiwiY2xpZW50Um9sZXMiOlsiZGV2Iiwic3VwZXJ1c2VyIl19.Ig2GkCJumkcxT_a83DBZz5buneKwi7NOhyByiBT9Wn0CqxWwWB1AXGvGPgQhmpKW5wxcRo6Q0GG6hb6qMmJPr0SbtB8xkOVozSYpCNEAAXc-Qr5qfcXFOc3IjYBNekbIBjR-EGVblZy4MzWi5gXVrT8oZ7AfZTquKdgiLEGCg-4Iuz94F1FygD8vKt8Zm0imjLfp-JxjK68c858EUvop0eTDyyD5n7ZCUgSjfkSk8hL8OgudSjVLkerlDRw1mCMaPyscuVSC_4F-2BV6Jjh9yEWIbrZ7cn5mLgaUcDLQAGulL76-OnpEiEWOX7d5ZzZD57fAghlM0LY-TECyVhh-IQ"
    connectionTimeout: 900000
    socketTimeout: 900000
  omopCdm:
    jdbcUrl: "jdbc:postgresql://127.0.0.1:5412/ohdsi"
    username: "ohdsi_admin_user"
    password: "admin1"
    schema: "cds_cdm"
  beginDate: "1800-01-01" # for example 2020-01-01
  endDate: "2099-12-31"

management:
  #  endpoints:
  #    web:
  #      exposure:
  #        include: "health,metrics,prometheus,info"
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: false
          base-url: "http://localhost:9091"
          push-rate: 10s
          job: "fhirtoomop"


thread:
  pool:
    size: 8

fhir:
  systems:
    #patient-id: "https://miracum.org/fhir/NamingSystem/identifier/PatientId"
    #encounter-supply-id: "https://miracum.org/fhir/NamingSystem/identifier/EncounterId"
    #encounter-department-id: "https://miracum.org/fhir/NamingSystem/identifier/EncounterId"
    #procedure-id: "https://diz.uniklinikum-dresden.de/fhir/core/NamingSystem/ProzedurId"
    #procedure-id: "https://miracum.org/fhir/NamingSystem/identifier/P21SurrogateProcedureId"
    #medication-administration-id: "https://diz.uniklinikum-dresden.de/fhir/core/NamingSystem/MedicationAdministrationId"
    #medication-id: "https://diz.uniklinikum-dresden.de/fhir/core/NamingSystem/MedicationId"
    #medication-statement-id: "https://diz.uniklinikum-dresden.de/fhir/core/NamingSystem/MedicationStatementId"
    #observation-id: "https://miracum.org/fhir/NamingSystem/identifier/P21SurrogateObservationId"
    #condition-id: "https://miracum.org/fhir/NamingSystem/identifier/P21SurrogateConditionId"
    loinc: "http://loinc.org"
    diagnostic-confidence: "http://fhir.de/StructureDefinition/icd-10-gm-diagnosesicherheit"
    diagnosis-use: "http://terminology.hl7.org/CodeSystem/diagnosis-role"
    interpretation: "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation"
    gender-amtlich-de-extension: "http://fhir.de/StructureDefinition/gender-amtlich-de"
    edqm: "http://standardterms.edqm.eu"
    identifier-type: "http://terminology.hl7.org/CodeSystem/v2-0203"
    snomed: "http://snomed.info/sct"
    ucum: "http://unitsofmeasure.org"
    orpha: "http://www.orpha.net"
    #department: "https://fhir.miracum.org/core/CodeSystem/fachabteilungen"
    department: "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/CodeSystem/Fachabteilungsschluessel"
    data-absent-reason: "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
    discharge-reason-structure: "https://www.medizininformatik-initiative.de/fhir/core/StructureDefinition/Entlassungsgrund"
    site-localization-extension: "http://fhir.de/StructureDefinition/seitenlokalisation"
    age-extension: "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/age"
    ethnic-group-extension: "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/ethnic-group"
    procedure-dicom: "http://dicom.nema.org/resources/ontology/DCM"
    vaccine-status-unknown: "http://hl7.org/fhir/uv/ips/CodeSystem/absent-unknown-uv-ips"
    clinical-status: "http://terminology.hl7.org/CodeSystem/condition-clinical"
    gecco-sofa-score: "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score"
    gecco-frailty-score: "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/frailty-score"
    gecco-biological-sex:
      - "http://hl7.org/fhir/administrative-gender"
      - "http://fhir.de/CodeSystem/gender-amtlich-de"
    verification-status:
      #- "http://snomed.info/sct"
      - "http://terminology.hl7.org/CodeSystem/condition-ver-status"
    gecco-ecrf-parameter: "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/ecrf-parameter-codes"
    gecco-components:
      - "http://loinc.org"
      - "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/sofa-score"
      - "http://snomed.info/sct"
    lab-observation-category:
      - "http://terminology.hl7.org/CodeSystem/observation-category"
      - "http://snomed.info/sct"
    observation-code:
      - "http://loinc.org"
      - "https://miracum.org/fhir/CodeSystem/p21/observations"
      - "http://snomed.info/sct"
      - "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/ecrf-parameter-codes"
      - "http://iprd.org/guides/anc/CodeSystem/iprd-custom-codes"
      - "http://fhir.org/guides/who/anc-cds/CodeSystem/anc-custom-codes"
      - "http://iprdgroup.com/guides/anc/CodeSystem/iprd-custom-codes"
      - "http://iprdsolutions.com/fhir/uv/anc/CodeSystem/iprd-custom-codes"
      - "https://iprdgroup.com/custom-codes"
      - "http://hl7.org/fhir/sid/icd-10"
    admission-reason:
      - "https://www.medizininformatik-initiative.de/fhir/core/CodeSystem/Aufnahmegrund"
      - "https://www.medizininformatik-initiative.de/fhir/modul-fall/core/CodeSystem/Aufnahmegrund"
    discharge-reason:
      - "https://www.medizininformatik-initiative.de/fhir/core/CodeSystem/Entlassungsgrund"
      - "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/CodeSystem/Entlassungsgrund"
    admission-occasion:
      - "https://www.medizininformatik-initiative.de/fhir/core/CodeSystem/Aufnahmeanlass"
      - "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/CodeSystem/Aufnahmeanlass"
    icd10gm:
      - "http://fhir.de/CodeSystem/dimdi/icd-10-gm"
      - "http://fhir.de/CodeSystem/bfarm/icd-10-gm"
      - "http://hl7.org/fhir/sid/icd-10"
    ops:
      - "http://fhir.de/CodeSystem/dimdi/ops"
      - "http://fhir.de/CodeSystem/bfarm/ops"
    atc:
      - "http://fhir.de/CodeSystem/dimdi/atc"
      - "http://fhir.de/CodeSystem/bfarm/atc"
    medication-codes:
      - "http://fhir.de/CodeSystem/dimdi/atc"
      - "http://fhir.de/CodeSystem/bfarm/atc"
      - "http://snomed.info/sct"
      - "http://www.nlm.nih.gov/research/umls/rxnorm"
    procedure-site-localization:
      - "https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_ICD_SEITENLOKALISATION"
      - "https://applications.kbv.de/S_ICD_SEITENLOKALISATION_V1.00.xhtml"
      - "http://snomed.info/sct"
    medication-route:
      - "http://snomed.info/sct"
      - "http://standardterms.edqm.eu"
    diagnose-code:
      - "http://fhir.de/CodeSystem/dimdi/icd-10-gm"
      - "http://fhir.de/CodeSystem/bfarm/icd-10-gm"
      - "http://snomed.info/sct"
      - "http://www.orpha.net"
      - "http://iprd.org/guides/anc/CodeSystem/iprd-custom-codes"
      - "http://fhir.org/guides/who/anc-cds/CodeSystem/anc-custom-codes"
      - "http://iprdgroup.com/guides/anc/CodeSystem/iprd-custom-codes"
      - "http://iprdsolutions.com/fhir/uv/anc/CodeSystem/iprd-custom-codes"
    vaccine-code:
      - "http://fhir.de/CodeSystem/dimdi/atc"
      - "http://fhir.de/CodeSystem/bfarm/atc"
      - "http://snomed.info/sct"
      - "http://fhir.org/guides/who/anc-cds/CodeSystem/anc-custom-codes"
      - "http://iprdgroup.com/guides/anc/CodeSystem/iprd-custom-codes"
      - "http://iprd.org/guides/anc/CodeSystem/iprd-custom-codes"
      - "http://iprdsolutions.com/fhir/uv/anc/CodeSystem/iprd-custom-codes"
    diagnostic-report-category:
      - "http://loinc.org"
      - "http://terminology.hl7.org/CodeSystem/v2-0074"
    identifier-system:
    tribe-extension: "http://iprdgroup.org/fhir/extention/tribe"
    occupation-extension: "http://fhir.org/guides/who/anc-cds/StructureDefinition/occupation"

opentracing:
  jaeger:
    enabled: false
    log-spans: false
    enable-b3-propagation: true
    # Doesn't work yet. Waiting for upstream opentracing lib to include
    # https://github.com/opentracing-contrib/java-spring-jaeger/commit/0b95db499ea57b9c43d7cfcb05dc74e01f67e287
    enable-w3c-propagation: true
    probabilistic-sampler:
      sampling-rate: 0.1
app:
  version: 0.0.0-dev
  bulkload:
    enabled: true
  dictionaryLoadInRam:
    enabled: true
  writeMedicationStatement:
    enabled: true
  startSingleStep: "" # Observation, Immunization, DiagnosticReport, Condition, MedicationAdministration, MedicationStatement, DepartmentCase or Procedure
