version: "3.7"

services:
  omopdb:
    image: harbor.miracum.org/miracum-etl/omop/init:v3.0.1-rc.1-cdm5.3.1
    ports:
      - "127.0.0.1:5434:5432"

  fhir-gateway-db:
    image: postgres:14.2
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir
    volumes:
      - ./init-test-data/:/docker-entrypoint-initdb.d/:ro
  pushgateway:
    image: prom/pushgateway:v1.4.2
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:v2.35.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  jaeger:
    image: jaegertracing/all-in-one:1.33
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp
