version: "3"
services:
  hapi-fhir-jpaserver:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir-server
    volumes:
      - ./data/hapi:/data/hapi
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - cloudbuild
      - default

  hapi-fhir-postgres:
    image: postgres:13-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
    networks:
      - cloudbuild
      - default

volumes:
  hapi-fhir-postgres:  
  
networks:
  cloudbuild:
    external: true
    name: cloudbuild # Needed for Continuous integration